name: Publish Service Extensions Callout images packages

# on push in the PR branch
on:
  push:
    branches:
      - 'flavien/service-extensions'

jobs:
  publish-service-extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        id: go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        shell: bash
        run: docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./contrib/envoyproxy/envoy/cmd/serviceextensions/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/datadog/dd-trace-go/service-extensions-callout:latest,ghcr.io/datadog/dd-trace-go/service-extensions-callout:${{ github.sha }}


